[phases.setup]
nixPkgs = [
  "php83",
  "composer",
  "php83Extensions.pdo",
  "php83Extensions.mbstring",
  "php83Extensions.bcmath",
  "php83Extensions.openssl"
]

[phases.install]
cmds = [
  "composer install --no-interaction --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan view:cache"
]