[phases.setup]
nixPkgs = [
  "php83",  # Gunakan PHP 8.3 yang lebih baru
  "composer",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.bcmath",
  "php83Extensions.curl",
  "php83Extensions.xml",
  "php83Extensions.fileinfo",
  "php83Extensions.tokenizer",
  "php83Extensions.openssl"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan view:cache",
  "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"